// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5W8UrLxj5Ge1BViEZ731rYPMWxMm3m8',
    appId: '1:42243577128:web:0814d2d29bee0b1739ec1d',
    messagingSenderId: '42243577128',
    projectId: 'tawazon-69d9b',
    authDomain: 'tawazon-69d9b.firebaseapp.com',
    storageBucket: 'tawazon-69d9b.firebasestorage.app',
    measurementId: 'G-NWCJE79RMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1kLczIwct1ZwRcIHBa4Wf7j3hGZguOQ',
    appId: '1:42243577128:android:5385c7a65f648b1c39ec1d',
    messagingSenderId: '42243577128',
    projectId: 'tawazon-69d9b',
    storageBucket: 'tawazon-69d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKtn-vYS_LBG9IjIN6RkuElM_tlZXZ7A',
    appId: '1:42243577128:ios:dc9ea71003b32c4339ec1d',
    messagingSenderId: '42243577128',
    projectId: 'tawazon-69d9b',
    storageBucket: 'tawazon-69d9b.firebasestorage.app',
    iosBundleId: 'com.example.base',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKtn-vYS_LBG9IjIN6RkuElM_tlZXZ7A',
    appId: '1:42243577128:ios:dc9ea71003b32c4339ec1d',
    messagingSenderId: '42243577128',
    projectId: 'tawazon-69d9b',
    storageBucket: 'tawazon-69d9b.firebasestorage.app',
    iosBundleId: 'com.example.base',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH5W8UrLxj5Ge1BViEZ731rYPMWxMm3m8',
    appId: '1:42243577128:web:b27232999a97833e39ec1d',
    messagingSenderId: '42243577128',
    projectId: 'tawazon-69d9b',
    authDomain: 'tawazon-69d9b.firebaseapp.com',
    storageBucket: 'tawazon-69d9b.firebasestorage.app',
    measurementId: 'G-XMTYYZDVJQ',
  );
}
